package injector

import (
	"io"
	"log/slog"
	"os"
	"strconv"
	"strings"
	"testing"

	"github.com/apm2go/apm2go/internal/assets"
	"github.com/apm2go/apm2go/internal/config"
	"github.com/apm2go/apm2go/internal/discovery"
	"github.com/apm2go/apm2go/internal/ingesttoken"
)

func newTestInjector(t *testing.T, cfg config.AttachConfig) *Injector {
	t.Helper()

	store, err := assets.New()
	if err != nil {
		t.Skipf("embedded agent jars not built (run `make assets` first): %v", err)
	}
	// helperPath is empty: these tests exercise property rendering, not a
	// real handshake, and Runner.canDropTo only rejects an empty path when a
	// privilege drop actually has to happen.
	inj, err := New(cfg, "/proc", "", store, ingesttoken.NewRegistry(), slog.New(slog.NewTextHandler(io.Discard, nil)))
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	return inj
}

func testJVM(pid int) *discovery.JVM {
	return &discovery.JVM{PID: pid, NSPid: pid, UID: 1000, GID: 1000, ServiceName: "orders"}
}

func baseConfig() config.AttachConfig {
	return config.AttachConfig{
		OTLPEndpoint:    "http://127.0.0.1:4317",
		MetricsInterval: 15_000_000_000,
		SampleRatio:     1.0,
		ExtraProperties: map[string]string{},
	}
}

// The configuration a real attach sends is small — a service name, an
// endpoint, a sample ratio, a resource-attribute list — and has to stay well
// under the budget that keeps it inline. This is what the fix actually buys:
// nothing about a normal attach should ever fall back to a file.
func TestRenderPropertiesFitsInlineForAnOrdinaryJVM(t *testing.T) {
	inj := newTestInjector(t, baseConfig())
	jvm := testJVM(4242)

	text, err := inj.renderProperties(jvm)
	if err != nil {
		t.Fatalf("renderProperties: %v", err)
	}
	if !strings.HasPrefix(text, "# Generated by apm2go for pid 4242") {
		t.Errorf("text does not start with the expected header:\n%s", text)
	}
	if !strings.Contains(text, "otel.service.name=orders") {
		t.Errorf("text is missing otel.service.name:\n%s", text)
	}

	jarPath := "/proc/4242/root/tmp/apm2go/apm2go-bootstrap-abc123.jar"
	if !fitsInline(jarPath, text) {
		t.Errorf("an ordinary JVM's configuration (%d bytes) does not fit inline; "+
			"every real attach would now silently fall back to a file", len(text))
	}
}

// An operator's own extra_properties has no size limit apm2go enforces, and a
// long enough one has to fall back to a file rather than being silently
// truncated by HotSpot's own argument cap.
func TestFitsInlineRejectsConfigurationTooLargeForOneAttachArgument(t *testing.T) {
	huge := strings.Repeat("a", inlineOptionBudget)
	if fitsInline("/proc/1/root/tmp/apm2go/bootstrap.jar", huge) {
		t.Error("a configuration this large was accepted as inline; it would be silently truncated")
	}
}

func TestFitsInlineAcceptsRightUpToTheBudget(t *testing.T) {
	jarPath := "/jar"
	// len(jarPath) + 1 ('=') + len(text) must be <= inlineOptionBudget.
	text := strings.Repeat("a", inlineOptionBudget-len(jarPath)-1)
	if !fitsInline(jarPath, text) {
		t.Error("a configuration exactly at the budget was rejected")
	}
	if fitsInline(jarPath, text+"a") {
		t.Error("a configuration one byte over the budget was accepted")
	}
}

// A long resource-attribute list -- a deep container id, a long systemd unit
// name, several extra_properties -- is the realistic way a real attach ends up
// over budget. This exercises the fallback path itself, not just the length
// arithmetic: writeConfigFile must produce a file BootstrapAgent can actually
// parse back into the same properties.
func TestRenderPropertiesFallsBackToFileWhenTooLargeToInline(t *testing.T) {
	cfg := baseConfig()
	for i := 0; i < 40; i++ {
		cfg.ExtraProperties["custom.property."+strconv.Itoa(i)] = strings.Repeat("x", 20)
	}
	inj := newTestInjector(t, cfg)
	jvm := testJVM(9999)

	text, err := inj.renderProperties(jvm)
	if err != nil {
		t.Fatalf("renderProperties: %v", err)
	}
	if fitsInline("/proc/9999/root/tmp/apm2go/apm2go-bootstrap-abc123.jar", text) {
		t.Fatalf("test setup did not produce a large enough configuration (%d bytes)", len(text))
	}

	dir := t.TempDir()
	path, err := inj.writeConfigFile(dir, text, jvm)
	if err != nil {
		t.Fatalf("writeConfigFile: %v", err)
	}
	written, err := readFile(path)
	if err != nil {
		t.Fatalf("read back %s: %v", path, err)
	}
	if written != text {
		t.Error("the file on disk does not match what renderProperties produced")
	}
}

func readFile(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	return string(data), nil
}
